version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
      - node_modules:/workspace/node_modules
    working_dir: /workspace
    tty: true

volumes:
  node_modules:
